#pragma once

#include "KswordArkProcessIoctl.h"

// ============================================================
// KswordArkTrustIoctl.h
// 作用：
// - 定义 Phase-14 镜像信任与 Code Integrity 只读查询协议；
// - R0 仅返回内核可观察的加载/缓存信任状态；
// - Authenticode 证书链、Catalog 和吊销检查后续由 R3 WinVerifyTrust 完成。
// ============================================================

#define KSWORD_ARK_TRUST_PROTOCOL_VERSION 1UL

#define KSWORD_ARK_IOCTL_FUNCTION_QUERY_IMAGE_TRUST 0x819UL

#define IOCTL_KSWORD_ARK_QUERY_IMAGE_TRUST \
    CTL_CODE( \
        KSWORD_ARK_IOCTL_DEVICE_TYPE, \
        KSWORD_ARK_IOCTL_FUNCTION_QUERY_IMAGE_TRUST, \
        METHOD_BUFFERED, \
        FILE_ANY_ACCESS)

#define KSWORD_ARK_TRUST_QUERY_FLAG_INCLUDE_GLOBAL_CI          0x00000001UL
#define KSWORD_ARK_TRUST_QUERY_FLAG_INCLUDE_FILE_SIGNING_LEVEL 0x00000002UL
#define KSWORD_ARK_TRUST_QUERY_FLAG_OPEN_REPARSE_POINT         0x00000004UL
#define KSWORD_ARK_TRUST_QUERY_FLAG_INCLUDE_ALL \
    (KSWORD_ARK_TRUST_QUERY_FLAG_INCLUDE_GLOBAL_CI | \
     KSWORD_ARK_TRUST_QUERY_FLAG_INCLUDE_FILE_SIGNING_LEVEL)

#define KSWORD_ARK_TRUST_FIELD_GLOBAL_CI_PRESENT          0x00000001UL
#define KSWORD_ARK_TRUST_FIELD_SECURE_BOOT_PRESENT        0x00000002UL
#define KSWORD_ARK_TRUST_FIELD_FILE_OPENED                0x00000004UL
#define KSWORD_ARK_TRUST_FIELD_FILE_OBJECT_PRESENT        0x00000008UL
#define KSWORD_ARK_TRUST_FIELD_SIGNING_LEVEL_PRESENT      0x00000010UL
#define KSWORD_ARK_TRUST_FIELD_THUMBPRINT_PRESENT         0x00000020UL
#define KSWORD_ARK_TRUST_FIELD_CI_VALIDATE_EXPORT_PRESENT 0x00000040UL
#define KSWORD_ARK_TRUST_FIELD_AUTHENTICODE_DEFERRED_R3   0x00000080UL
#define KSWORD_ARK_TRUST_FIELD_REQUEST_PATH_PRESENT       0x00000100UL

#define KSWORD_ARK_TRUST_STATUS_UNAVAILABLE                 0UL
#define KSWORD_ARK_TRUST_STATUS_OK                          1UL
#define KSWORD_ARK_TRUST_STATUS_PARTIAL                     2UL
#define KSWORD_ARK_TRUST_STATUS_FILE_OPEN_FAILED            3UL
#define KSWORD_ARK_TRUST_STATUS_SIGNING_LEVEL_UNAVAILABLE   4UL
#define KSWORD_ARK_TRUST_STATUS_CI_UNAVAILABLE              5UL
#define KSWORD_ARK_TRUST_STATUS_INVALID_REQUEST             6UL

#define KSWORD_ARK_TRUST_SOURCE_NONE                    0UL
#define KSWORD_ARK_TRUST_SOURCE_SYSTEM_CODE_INTEGRITY   1UL
#define KSWORD_ARK_TRUST_SOURCE_SE_CACHED_SIGNING_LEVEL 2UL
#define KSWORD_ARK_TRUST_SOURCE_R3_AUTHENTICODE_PENDING 3UL

#define KSWORD_ARK_SIGNING_LEVEL_UNCHECKED       0U
#define KSWORD_ARK_SIGNING_LEVEL_UNSIGNED        1U
#define KSWORD_ARK_SIGNING_LEVEL_ENTERPRISE      2U
#define KSWORD_ARK_SIGNING_LEVEL_DEVELOPER       3U
#define KSWORD_ARK_SIGNING_LEVEL_AUTHENTICODE    4U
#define KSWORD_ARK_SIGNING_LEVEL_CUSTOM_2        5U
#define KSWORD_ARK_SIGNING_LEVEL_STORE           6U
#define KSWORD_ARK_SIGNING_LEVEL_ANTIMALWARE     7U
#define KSWORD_ARK_SIGNING_LEVEL_MICROSOFT       8U
#define KSWORD_ARK_SIGNING_LEVEL_CUSTOM_4        9U
#define KSWORD_ARK_SIGNING_LEVEL_CUSTOM_5        10U
#define KSWORD_ARK_SIGNING_LEVEL_DYNAMIC_CODEGEN 11U
#define KSWORD_ARK_SIGNING_LEVEL_WINDOWS         12U
#define KSWORD_ARK_SIGNING_LEVEL_CUSTOM_7        13U
#define KSWORD_ARK_SIGNING_LEVEL_WINDOWS_TCB     14U
#define KSWORD_ARK_SIGNING_LEVEL_CUSTOM_6        15U

#define KSWORD_ARK_CODEINTEGRITY_OPTION_ENABLED                 0x00000001UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_TESTSIGN                0x00000002UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_UMCI_ENABLED            0x00000004UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_UMCI_AUDITMODE_ENABLED  0x00000008UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_TEST_BUILD              0x00000020UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_DEBUGMODE_ENABLED       0x00000080UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_FLIGHT_BUILD            0x00000100UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_FLIGHTING_ENABLED       0x00000200UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_HVCI_KMCI_ENABLED       0x00000400UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_HVCI_KMCI_AUDITMODE     0x00000800UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_HVCI_KMCI_STRICTMODE    0x00001000UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_HVCI_IUM_ENABLED        0x00002000UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_WHQL_ENFORCEMENT        0x00004000UL
#define KSWORD_ARK_CODEINTEGRITY_OPTION_WHQL_AUDITMODE          0x00008000UL

#define KSWORD_ARK_TRUST_PATH_MAX_CHARS 1024U
#define KSWORD_ARK_TRUST_THUMBPRINT_MAX_BYTES 64U

typedef struct _KSWORD_ARK_QUERY_IMAGE_TRUST_REQUEST
{
    unsigned long flags;
    unsigned short pathLengthChars;
    unsigned short reserved;
    wchar_t path[KSWORD_ARK_TRUST_PATH_MAX_CHARS];
} KSWORD_ARK_QUERY_IMAGE_TRUST_REQUEST;

typedef struct _KSWORD_ARK_QUERY_IMAGE_TRUST_RESPONSE
{
    unsigned long version;
    unsigned long size;
    unsigned long fieldFlags;
    unsigned long queryStatus;
    unsigned long trustSource;
    unsigned long signingLevel;
    unsigned long signingLevelFlags;
    unsigned long thumbprintAlgorithm;
    unsigned long thumbprintSize;
    unsigned long codeIntegrityOptions;
    unsigned long secureBootEnabled;
    unsigned long secureBootCapable;
    long codeIntegrityStatus;
    long secureBootStatus;
    long openStatus;
    long objectStatus;
    long signingLevelStatus;
    unsigned long long fileObjectAddress;
    unsigned char thumbprint[KSWORD_ARK_TRUST_THUMBPRINT_MAX_BYTES];
    wchar_t ntPath[KSWORD_ARK_TRUST_PATH_MAX_CHARS];
} KSWORD_ARK_QUERY_IMAGE_TRUST_RESPONSE;
