#pragma once

#include "KswordArkProcessIoctl.h"

// ============================================================
// KswordArkDynDataIoctl.h
// Purpose:
// - Shared R3/R0 protocol for querying DynData profile status, field offsets,
//   and derived feature capability flags.
// - This file is the only shared protocol surface for Phase 0 DynData queries.
// ============================================================

#define KSWORD_ARK_DYNDATA_PROTOCOL_VERSION 1UL

#define KSWORD_ARK_IOCTL_FUNCTION_QUERY_DYN_STATUS 0x807
#define KSWORD_ARK_IOCTL_FUNCTION_QUERY_DYN_FIELDS 0x808
#define KSWORD_ARK_IOCTL_FUNCTION_QUERY_CAPABILITIES 0x809
#define KSWORD_ARK_IOCTL_FUNCTION_APPLY_DYN_PROFILE 0x82F
#define KSWORD_ARK_IOCTL_FUNCTION_APPLY_DYN_PROFILE_EX 0x830

#define IOCTL_KSWORD_ARK_QUERY_DYN_STATUS \
    CTL_CODE( \
        KSWORD_ARK_IOCTL_DEVICE_TYPE, \
        KSWORD_ARK_IOCTL_FUNCTION_QUERY_DYN_STATUS, \
        METHOD_BUFFERED, \
        FILE_ANY_ACCESS)

#define IOCTL_KSWORD_ARK_QUERY_DYN_FIELDS \
    CTL_CODE( \
        KSWORD_ARK_IOCTL_DEVICE_TYPE, \
        KSWORD_ARK_IOCTL_FUNCTION_QUERY_DYN_FIELDS, \
        METHOD_BUFFERED, \
        FILE_ANY_ACCESS)

#define IOCTL_KSWORD_ARK_QUERY_CAPABILITIES \
    CTL_CODE( \
        KSWORD_ARK_IOCTL_DEVICE_TYPE, \
        KSWORD_ARK_IOCTL_FUNCTION_QUERY_CAPABILITIES, \
        METHOD_BUFFERED, \
        FILE_ANY_ACCESS)

#define IOCTL_KSWORD_ARK_APPLY_DYN_PROFILE \
    CTL_CODE( \
        KSWORD_ARK_IOCTL_DEVICE_TYPE, \
        KSWORD_ARK_IOCTL_FUNCTION_APPLY_DYN_PROFILE, \
        METHOD_BUFFERED, \
        FILE_WRITE_ACCESS)

#define IOCTL_KSWORD_ARK_APPLY_DYN_PROFILE_EX \
    CTL_CODE( \
        KSWORD_ARK_IOCTL_DEVICE_TYPE, \
        KSWORD_ARK_IOCTL_FUNCTION_APPLY_DYN_PROFILE_EX, \
        METHOD_BUFFERED, \
        FILE_WRITE_ACCESS)

#define KSW_CAP_DYN_NTOS_ACTIVE             0x0000000000000001ULL
#define KSW_CAP_DYN_LXCORE_ACTIVE           0x0000000000000002ULL
#define KSW_CAP_OBJECT_TYPE_FIELDS          0x0000000000000004ULL
#define KSW_CAP_HANDLE_TABLE_DECODE         0x0000000000000008ULL
#define KSW_CAP_PROCESS_OBJECT_TABLE        0x0000000000000010ULL
#define KSW_CAP_THREAD_STACK_FIELDS         0x0000000000000020ULL
#define KSW_CAP_THREAD_IO_COUNTERS          0x0000000000000040ULL
#define KSW_CAP_ALPC_FIELDS                 0x0000000000000080ULL
#define KSW_CAP_SECTION_CONTROL_AREA        0x0000000000000100ULL
#define KSW_CAP_PROCESS_PROTECTION_PATCH    0x0000000000000200ULL
#define KSW_CAP_WSL_LXCORE_FIELDS           0x0000000000000400ULL
#define KSW_CAP_ETW_GUID_FIELDS             0x0000000000000800ULL
#define KSW_CAP_CALLBACK_NOTIFY_GLOBALS     0x0000000000001000ULL
#define KSW_CAP_CALLBACK_REGISTRY_GLOBALS   0x0000000000002000ULL
#define KSW_CAP_CALLBACK_OBJECT_FIELDS      0x0000000000004000ULL
#define KSW_CAP_PROCESS_LIST_FIELDS         0x0000000000008000ULL
#define KSW_CAP_THREAD_LIST_FIELDS          0x0000000000010000ULL
#define KSW_CAP_CID_TABLE_WALK              0x0000000000020000ULL
#define KSW_CAP_KERNEL_MODULE_LIST_FIELDS   0x0000000000040000ULL
#define KSW_CAP_DRIVER_OBJECT_FIELDS        0x0000000000080000ULL
#define KSW_CAP_KERNEL_GLOBALS              0x0000000000100000ULL

#define KSW_DYN_STATUS_FLAG_INITIALIZED      0x00000001UL
#define KSW_DYN_STATUS_FLAG_NTOS_ACTIVE      0x00000002UL
#define KSW_DYN_STATUS_FLAG_LXCORE_ACTIVE    0x00000004UL
#define KSW_DYN_STATUS_FLAG_EXTRA_ACTIVE     0x00000008UL
#define KSW_DYN_STATUS_FLAG_PDB_PROFILE_ACTIVE 0x00000010UL
#define KSW_DYN_STATUS_FLAG_CALLBACK_PROFILE_ACTIVE 0x00000020UL

#define KSW_DYN_MODULE_NAME_CHARS 64U
#define KSW_DYN_REASON_CHARS 160U
#define KSW_DYN_FIELD_NAME_CHARS 64U
#define KSW_DYN_FIELD_SOURCE_CHARS 32U
#define KSW_DYN_FIELD_FEATURE_CHARS 64U
#define KSW_DYN_PROFILE_NAME_CHARS 96U
#define KSW_DYN_PDB_NAME_CHARS 64U
#define KSW_DYN_PDB_GUID_CHARS 40U
#define KSW_DYN_PROFILE_MAX_FIELDS 128U
#define KSW_DYN_PROFILE_EX_MAX_ITEMS 256U
#define KSW_DYN_PROFILE_OFFSET_MAX 0x0000FFFFUL
#define KSW_DYN_PROFILE_GLOBAL_RVA_MAX 0x7FFFFFFFUL
#define KSW_DYN_PROFILE_FLAG_TRANSPORT_IOCTL 0x00000001UL
#define KSW_DYN_PROFILE_FLAG_TRANSPORT_SECTION_RESERVED 0x00000002UL

#define KSW_DYN_PROFILE_CLASS_NTOSKRNL 0U
#define KSW_DYN_PROFILE_CLASS_NTKRLA57 1U
#define KSW_DYN_PROFILE_CLASS_LXCORE 2U

#define KSW_DYN_FIELD_SOURCE_UNAVAILABLE 0UL
#define KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER 1UL
#define KSW_DYN_FIELD_SOURCE_RUNTIME_PATTERN 2UL
#define KSW_DYN_FIELD_SOURCE_KSWORD_EXTRA_TABLE 3UL
#define KSW_DYN_FIELD_SOURCE_PDB_PROFILE 4UL

#define KSW_DYN_FIELD_FLAG_PRESENT 0x00000001UL
#define KSW_DYN_FIELD_FLAG_REQUIRED 0x00000002UL
#define KSW_DYN_FIELD_FLAG_OPTIONAL 0x00000004UL

#define KSW_DYN_FIELD_ID_EP_OBJECT_TABLE 1UL
#define KSW_DYN_FIELD_ID_EP_SECTION_OBJECT 2UL
#define KSW_DYN_FIELD_ID_HT_HANDLE_CONTENTION_EVENT 3UL
#define KSW_DYN_FIELD_ID_OT_NAME 4UL
#define KSW_DYN_FIELD_ID_OT_INDEX 5UL
#define KSW_DYN_FIELD_ID_OB_DECODE_SHIFT 6UL
#define KSW_DYN_FIELD_ID_OB_ATTRIBUTES_SHIFT 7UL
#define KSW_DYN_FIELD_ID_KT_INITIAL_STACK 8UL
#define KSW_DYN_FIELD_ID_KT_STACK_LIMIT 9UL
#define KSW_DYN_FIELD_ID_KT_STACK_BASE 10UL
#define KSW_DYN_FIELD_ID_KT_KERNEL_STACK 11UL
#define KSW_DYN_FIELD_ID_KT_READ_OPERATION_COUNT 12UL
#define KSW_DYN_FIELD_ID_KT_WRITE_OPERATION_COUNT 13UL
#define KSW_DYN_FIELD_ID_KT_OTHER_OPERATION_COUNT 14UL
#define KSW_DYN_FIELD_ID_KT_READ_TRANSFER_COUNT 15UL
#define KSW_DYN_FIELD_ID_KT_WRITE_TRANSFER_COUNT 16UL
#define KSW_DYN_FIELD_ID_KT_OTHER_TRANSFER_COUNT 17UL
#define KSW_DYN_FIELD_ID_MM_SECTION_CONTROL_AREA 18UL
#define KSW_DYN_FIELD_ID_MM_CONTROL_AREA_LIST_HEAD 19UL
#define KSW_DYN_FIELD_ID_MM_CONTROL_AREA_LOCK 20UL
#define KSW_DYN_FIELD_ID_ALPC_COMMUNICATION_INFO 21UL
#define KSW_DYN_FIELD_ID_ALPC_OWNER_PROCESS 22UL
#define KSW_DYN_FIELD_ID_ALPC_CONNECTION_PORT 23UL
#define KSW_DYN_FIELD_ID_ALPC_SERVER_COMMUNICATION_PORT 24UL
#define KSW_DYN_FIELD_ID_ALPC_CLIENT_COMMUNICATION_PORT 25UL
#define KSW_DYN_FIELD_ID_ALPC_HANDLE_TABLE 26UL
#define KSW_DYN_FIELD_ID_ALPC_HANDLE_TABLE_LOCK 27UL
#define KSW_DYN_FIELD_ID_ALPC_ATTRIBUTES 28UL
#define KSW_DYN_FIELD_ID_ALPC_ATTRIBUTES_FLAGS 29UL
#define KSW_DYN_FIELD_ID_ALPC_PORT_CONTEXT 30UL
#define KSW_DYN_FIELD_ID_ALPC_PORT_OBJECT_LOCK 31UL
#define KSW_DYN_FIELD_ID_ALPC_SEQUENCE_NO 32UL
#define KSW_DYN_FIELD_ID_ALPC_STATE 33UL
#define KSW_DYN_FIELD_ID_LX_PICO_PROC 34UL
#define KSW_DYN_FIELD_ID_LX_PICO_PROC_INFO 35UL
#define KSW_DYN_FIELD_ID_LX_PICO_PROC_INFO_PID 36UL
#define KSW_DYN_FIELD_ID_LX_PICO_THRD_INFO 37UL
#define KSW_DYN_FIELD_ID_LX_PICO_THRD_INFO_TID 38UL
#define KSW_DYN_FIELD_ID_EP_PROTECTION 39UL
#define KSW_DYN_FIELD_ID_EP_SIGNATURE_LEVEL 40UL
#define KSW_DYN_FIELD_ID_EP_SECTION_SIGNATURE_LEVEL 41UL
#define KSW_DYN_FIELD_ID_EGE_GUID 42UL
#define KSW_DYN_FIELD_ID_ERE_GUID_ENTRY 43UL
#define KSW_DYN_FIELD_ID_CB_PSP_CREATE_PROCESS_NOTIFY_ROUTINE 44UL
#define KSW_DYN_FIELD_ID_CB_PSP_CREATE_THREAD_NOTIFY_ROUTINE 45UL
#define KSW_DYN_FIELD_ID_CB_PSP_LOAD_IMAGE_NOTIFY_ROUTINE 46UL
#define KSW_DYN_FIELD_ID_CB_PSP_NOTIFY_ENABLE_MASK 47UL
#define KSW_DYN_FIELD_ID_CB_CM_CALLBACK_LIST_HEAD 48UL
#define KSW_DYN_FIELD_ID_CB_OBJECT_TYPE_CALLBACK_LIST 49UL
#define KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_ENTRY_LIST 50UL
#define KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_PRE_OPERATION 51UL
#define KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_POST_OPERATION 52UL
#define KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_OPERATIONS 53UL
#define KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_CALLBACK_ENTRY 54UL
#define KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ALTITUDE 55UL
#define KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_REGISTRATION_CONTEXT 56UL
#define KSW_DYN_FIELD_ID_EP_UNIQUE_PROCESS_ID 57UL
#define KSW_DYN_FIELD_ID_EP_ACTIVE_PROCESS_LINKS 58UL
#define KSW_DYN_FIELD_ID_EP_THREAD_LIST_HEAD 59UL
#define KSW_DYN_FIELD_ID_EP_IMAGE_FILE_NAME 60UL
#define KSW_DYN_FIELD_ID_EP_TOKEN 61UL
#define KSW_DYN_FIELD_ID_ET_CID 62UL
#define KSW_DYN_FIELD_ID_ET_THREAD_LIST_ENTRY 63UL
#define KSW_DYN_FIELD_ID_ET_START_ADDRESS 64UL
#define KSW_DYN_FIELD_ID_ET_WIN32_START_ADDRESS 65UL
#define KSW_DYN_FIELD_ID_KT_PROCESS 66UL
#define KSW_DYN_FIELD_ID_HT_TABLE_CODE 67UL
#define KSW_DYN_FIELD_ID_HT_HANDLE_COUNT 68UL
#define KSW_DYN_FIELD_ID_HTE_LOW_VALUE 69UL
#define KSW_DYN_FIELD_ID_KLDR_IN_LOAD_ORDER_LINKS 70UL
#define KSW_DYN_FIELD_ID_KLDR_DLL_BASE 71UL
#define KSW_DYN_FIELD_ID_KLDR_SIZE_OF_IMAGE 72UL
#define KSW_DYN_FIELD_ID_KLDR_FULL_DLL_NAME 73UL
#define KSW_DYN_FIELD_ID_KLDR_BASE_DLL_NAME 74UL
#define KSW_DYN_FIELD_ID_KLDR_FLAGS 75UL
#define KSW_DYN_FIELD_ID_DO_DRIVER_START 76UL
#define KSW_DYN_FIELD_ID_DO_DRIVER_SIZE 77UL
#define KSW_DYN_FIELD_ID_DO_DRIVER_SECTION 78UL
#define KSW_DYN_FIELD_ID_DO_MAJOR_FUNCTION 79UL
#define KSW_DYN_FIELD_ID_DO_FAST_IO_DISPATCH 80UL
#define KSW_DYN_FIELD_ID_DO_DRIVER_UNLOAD 81UL
#define KSW_DYN_FIELD_ID_KG_PSP_CID_TABLE 82UL
#define KSW_DYN_FIELD_ID_KG_PS_LOADED_MODULE_LIST 83UL
#define KSW_DYN_FIELD_ID_KG_MM_UNLOADED_DRIVERS 84UL
#define KSW_DYN_FIELD_ID_KG_PIDDB_CACHE_TABLE 85UL
#define KSW_DYN_FIELD_ID_MAX KSW_DYN_FIELD_ID_KG_PIDDB_CACHE_TABLE

#define KSW_DYN_PROFILE_EX_ITEM_KIND_STRUCT_OFFSET 1UL
#define KSW_DYN_PROFILE_EX_ITEM_KIND_GLOBAL_RVA 2UL

#define KSW_DYN_PROFILE_EX_ITEM_FLAG_REQUIRED 0x00000001UL
#define KSW_DYN_PROFILE_EX_ITEM_FLAG_CALLBACK 0x00000002UL

typedef struct _KSW_DYN_MODULE_IDENTITY_PACKET
{
    unsigned long present;
    unsigned long classId;
    unsigned long machine;
    unsigned long timeDateStamp;
    unsigned long sizeOfImage;
    unsigned long long imageBase;
    wchar_t moduleName[KSW_DYN_MODULE_NAME_CHARS];
} KSW_DYN_MODULE_IDENTITY_PACKET;

typedef struct _KSW_DYN_PROFILE_FIELD_PACKET
{
    unsigned long fieldId;
    unsigned long offset;
} KSW_DYN_PROFILE_FIELD_PACKET;

typedef struct _KSW_APPLY_DYN_PROFILE_REQUEST
{
    unsigned long size;
    unsigned long version;
    unsigned long flags;
    unsigned long fieldCount;
    KSW_DYN_MODULE_IDENTITY_PACKET ntoskrnl;
    char profileName[KSW_DYN_PROFILE_NAME_CHARS];
    char pdbName[KSW_DYN_PDB_NAME_CHARS];
    char pdbGuid[KSW_DYN_PDB_GUID_CHARS];
    unsigned long pdbAge;
    unsigned long reserved;
    KSW_DYN_PROFILE_FIELD_PACKET fields[1];
} KSW_APPLY_DYN_PROFILE_REQUEST;

#define KSW_APPLY_DYN_PROFILE_REQUEST_HEADER_SIZE \
    (sizeof(KSW_APPLY_DYN_PROFILE_REQUEST) - sizeof(KSW_DYN_PROFILE_FIELD_PACKET))

typedef struct _KSW_APPLY_DYN_PROFILE_RESPONSE
{
    unsigned long size;
    unsigned long version;
    long status;
    unsigned long appliedFieldCount;
    unsigned long rejectedFieldCount;
    unsigned long unknownFieldCount;
    unsigned long statusFlags;
    unsigned long long capabilityMask;
    wchar_t message[KSW_DYN_REASON_CHARS];
} KSW_APPLY_DYN_PROFILE_RESPONSE;

typedef struct _KSW_DYN_PROFILE_EX_ITEM_PACKET
{
    unsigned long itemId;
    unsigned long itemKind;
    unsigned long value;
    unsigned long flags;
} KSW_DYN_PROFILE_EX_ITEM_PACKET;

typedef struct _KSW_APPLY_DYN_PROFILE_EX_REQUEST
{
    unsigned long size;
    unsigned long version;
    unsigned long flags;
    unsigned long itemCount;
    KSW_DYN_MODULE_IDENTITY_PACKET ntoskrnl;
    char profileName[KSW_DYN_PROFILE_NAME_CHARS];
    char pdbName[KSW_DYN_PDB_NAME_CHARS];
    char pdbGuid[KSW_DYN_PDB_GUID_CHARS];
    unsigned long pdbAge;
    unsigned long reserved;
    KSW_DYN_PROFILE_EX_ITEM_PACKET items[1];
} KSW_APPLY_DYN_PROFILE_EX_REQUEST;

#define KSW_APPLY_DYN_PROFILE_EX_REQUEST_HEADER_SIZE \
    (sizeof(KSW_APPLY_DYN_PROFILE_EX_REQUEST) - sizeof(KSW_DYN_PROFILE_EX_ITEM_PACKET))

typedef struct _KSW_APPLY_DYN_PROFILE_EX_RESPONSE
{
    unsigned long size;
    unsigned long version;
    long status;
    unsigned long appliedItemCount;
    unsigned long rejectedItemCount;
    unsigned long unknownItemCount;
    unsigned long statusFlags;
    unsigned long long capabilityMask;
    wchar_t message[KSW_DYN_REASON_CHARS];
} KSW_APPLY_DYN_PROFILE_EX_RESPONSE;

typedef struct _KSW_QUERY_DYN_STATUS_RESPONSE
{
    unsigned long size;
    unsigned long version;
    unsigned long statusFlags;
    unsigned long systemInformerDataVersion;
    unsigned long systemInformerDataLength;
    long lastStatus;
    unsigned long matchedProfileClass;
    unsigned long matchedProfileOffset;
    unsigned long matchedFieldsId;
    unsigned long fieldCount;
    unsigned long reserved;
    unsigned long long capabilityMask;
    KSW_DYN_MODULE_IDENTITY_PACKET ntoskrnl;
    KSW_DYN_MODULE_IDENTITY_PACKET lxcore;
    wchar_t unavailableReason[KSW_DYN_REASON_CHARS];
} KSW_QUERY_DYN_STATUS_RESPONSE;

typedef struct _KSW_QUERY_CAPABILITIES_RESPONSE
{
    unsigned long size;
    unsigned long version;
    unsigned long statusFlags;
    unsigned long reserved;
    unsigned long long capabilityMask;
} KSW_QUERY_CAPABILITIES_RESPONSE;

typedef struct _KSW_DYN_FIELD_ENTRY
{
    unsigned long fieldId;
    unsigned long flags;
    unsigned long source;
    unsigned long offset;
    unsigned long long capabilityMask;
    char fieldName[KSW_DYN_FIELD_NAME_CHARS];
    char sourceName[KSW_DYN_FIELD_SOURCE_CHARS];
    char featureName[KSW_DYN_FIELD_FEATURE_CHARS];
} KSW_DYN_FIELD_ENTRY;

typedef struct _KSW_QUERY_DYN_FIELDS_RESPONSE
{
    unsigned long size;
    unsigned long version;
    unsigned long totalCount;
    unsigned long returnedCount;
    unsigned long entrySize;
    unsigned long reserved;
    KSW_DYN_FIELD_ENTRY entries[1];
} KSW_QUERY_DYN_FIELDS_RESPONSE;
