#ifndef _SHOW_LOGO_CPP_

#define _SHOW_LOGO_CPP_

#endif

// Shows the logo of "Kali" for you.

int show_logo()
{
    cprint("====================Kali Sword V1.3 For Public=====================", 87);
    cout << endl;
    cout << "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" << endl;
    cout << "~~~~~~~~~~";
    cprint("KKKKKKK", 87);
    cout << "~~";
    cprint("KKKKKK", 87);
    cout << "~~~~~~~~~~~~~~~~~";
    cprint("KKKKKKK", 87);
    cout << "~~~~~";
    cprint("KKKKKKK", 87);
    cout << "~~~~~" << endl;
    cout << "~~~~~~~~~~";
    cprint("KKKKKKK", 87);
    cout << "~~";
    cprint("KKKKKK", 87);
    cout << "~~~~~~~";
    cprint("KK", 87);
    cout << "~~~~~~~~~~";
    cprint("KKKKK", 87);
    cout << "~~~~~";
    cprint("KKKKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~";
    cprint("KK", 87);
    cout << "~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~";
    cprint("KK", 87);
    cout << "~~~~~~~~~~~";
    cprint("KKKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~~~~";
    cprint("K", 87);
    cout << "~";
    cprint("KKK", 87);
    cout << "~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKKKKK", 87);
    cout << "~~~~~~~~~~~~";
    cprint("KK", 87);
    cout << "~~";
    cprint("KK", 87);
    cout << "~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKKKKK", 87);
    cout << "~~~~~~~~~~~~";
    cprint("KKKKKK", 87);
    cout << "~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~~~";
    cprint("KKKKKKK", 87);
    cout << "~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~";
    cprint("KKK", 87);
    cout << "~~~~~~~~~";
    cprint("KK", 87);
    cout << "~~~~";
    cprint("KK", 87);
    cout << "~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~";
    cprint("K", 87);
    cout << "~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cprint("K", 87);
    cout << "~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~~";
    cprint("K", 87);
    cout << "~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~";
    cprint("KK", 87);
    cout << "~~~~~~";
    cprint("KK", 87);
    cout << "~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~";
    cprint("KK", 87);
    cout << "~~";
    cprint("KKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~";
    cprint("KKK", 87);
    cout << "~~~~~";
    cprint("KKKK", 87);
    cout << "~~~~";
    cprint("KKKK", 87);
    cout << "~~~~";
    cprint("KK", 87);
    cout << "~~~~~~";
    cprint("KKKKKKKKKKKKKKK", 87);
    cout << "~~~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~";
    cprint("KKKKKKK", 87);
    cout << "~~";
    cprint("KKKKKKKKKKKKK", 87);
    cout << "~~";
    cprint("KKKKKK", 87);
    cout << "~~";
    cprint("KKKKKKKKKKKKKKKKKKK", 87);
    cout << "~~~~~";
    cout << endl;
    cout << "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~";
    cout << endl;
}