//#pragma once
//#include <windows.h>
//
//
//extern "C"  __declspec(dllexport) BOOL EnumProcess();
//
//typedef struct _DATA_INFO_
//{
//    HANDLE handledata1;
//    HANDLE handledata2;
//    HANDLE handledata3;
//    HANDLE handledata4;
//    PVOID pvoidaddressdata1;
//    PVOID pvoidaddressdata2;
//    PVOID pvoidaddressdata3;
//    PVOID pvoidaddressdata4;
//    ULONG ulongdata1;
//    ULONG ulongdata2;
//    ULONG ulongdata3;
//    ULONG ulongdata4;
//    ULONG64 ulong64data1;
//    ULONG64 ulong64data2;
//    ULONG64 ulong64data3;
//    ULONG64 ulong64data4;
//    PUCHAR puchardata1;
//    char Module[MAX_PATH];
//    char Module1[MAX_PATH];
//    WCHAR wcstr[MAX_PATH];
//}DATA_INFO, * PDATA_INFO;
//
//typedef struct _DRIVER_INFOS_
//{
//    ULONG_PTR nLodeOrder;
//    ULONG_PTR nBase;
//    ULONG_PTR nSize;
//    ULONG_PTR nDriverObject;
//    char szDriverPath[MAX_PATH];
//    char szDriverName[MAX_PATH];
//}DRIVER_INFOS, * PDRIVER_INFOS;
//
//typedef struct _ALL_DRIVERSS_
//{
//    ULONG nCnt;
//    DRIVER_INFOS Drivers[1];
//}ALL_DRIVERSS, * PALL_DRIVERSS;
//
//
//typedef struct
//{
//    int Type;
//    int RegOp;
//    ULONG64 SectorRange;
//    ULONG Disk_DeviceType;
//    HANDLE hProcessId;
//    HANDLE hpParProcessId;
//    BOOLEAN bIsCreateMark;
//    WCHAR Loaded_DriverPath[256];
//    PVOID DriverEntryPoint;
//}PROCESS_PTR, * PPROCESS_PTR;
//
//typedef struct _SSSDT_INFOS_
//{
//    ULONG index;
//    PVOID Address;
//    char FunctionName[MAX_PATH];
//    char Module[MAX_PATH];
//}SSSDT_INFOS, * PSSSDT_INFOS;
//
//typedef struct _ALL_SSSDT_
//{
//    ULONG nCnt;
//    SSSDT_INFOS sssdt[1];
//}ALL_SSSDT, * PALL_SSSDT;
//enum pKEventType
//{
//    Event_Registry,
//    Event_CreateProcess,
//    Event_LoadDriver,
//    Event_File
//}pKEventType, * PpKEventType;
//
//enum pRegistryOperType
//{
//    REG_Create,
//    REG_Delete,
//    REG_Rename
//}pRegistryOperType, * PpRegistryOperType;
//
//enum pIrpHookScan
//{
//    IrpHook_NTOSKRNL,
//    IrpHook_DISK,
//    IrpHook_FSD,
//    IrpHook_NULL,
//    IrpHook_BEEP,
//    IrpHook_TCPIP
//}pIrpHookScan, * PpIrpHookScan;
//
//struct Kernel_MemoryOperation {
//    ULONG_PTR Address;
//    ULONG Size;
//};
//
//typedef struct _KERNEL_MEMORY_REQUEST {
//    ULONG_PTR Address;
//    ULONG Size;
//} KERNEL_MEMORY_REQUEST, * PKERNEL_MEMORY_REQUEST;
//
//enum RemoveNotifyType
//{
//    Notify_CreateProcess,
//    Notify_CreateThread,
//    Notify_Registry,
//    Notify_Loadimage,
//    Notify_BugCheck,
//    Notify_BugCheckReason,
//    Notify_Shutdown,
//    Notify_LoastShutdown,
//    Notify_FsNotofy,
//    Notify_PowerSetting,
//    Notify_Coalescing,
//    Notify_Priority,
//    Notify_DbgPrint,
//    Notify_ObCllback,
//    Notify_NmiCallback,
//    Notify_PlugPlay,
//    Notify_EmpCallback
//}RemoveNotifyType, * pRemoveNotifyType;
//
//typedef enum _KTHREAD_STATE
//{
//    ThreadState_Initialized,
//    ThreadState_Ready,
//    ThreadState_Running,
//    ThreadState_Standby,
//    ThreadState_Terminated,
//    ThreadState_Waiting,
//    ThreadState_Transition,
//    ThreadState_DeferredReady,
//    ThreadState_GateWait
//} KTHREAD_STATE, * PKTHREAD_STATE;
//
//typedef struct
//{
//    ULONG64 size;
//    BYTE* data;
//}KMemReadsData;
//
//enum pTokenModifyType
//{
//    MToken_System,
//    MToken_TrustedInstaller,
//    MToken_DWM,
//    MToken_UMDF
//}pTokenModifyType, * PpTokenModifyType;
//
//enum CrashSystemColorType
//{
//    CrashColor_Red,
//    CrashColor_Green,
//    CrashColor_Blue,
//    CrashColor_Yellow,
//    CrashColor_Cyan,
//    CrashColor_Magenta,
//    CrashColor_Black,
//    CrashColor_White,
//    CrashColor_Orange,
//    CrashColor_Purple,
//    CrashColor_Pink,
//    CrashColor_Grey,
//    CrashColor_Brown,
//    CrashColor_Gold,
//    CrashColor_Silver
//}CrashSystemColorType, * pCrashSystemColorType;
//
//#define PPL_System 0x71
//#define PPL_WinTcb 0x61
//#define PPL_Windows 0x51
//#define PPL_Lsa 0x41
//#define PPL_Antimalware 0x31
//#define PPL_CodeGen 0x21
//#define PPL_AuthentiCode 0x11
//#define PP_System 0x72
//#define PP_WinTcb 0x62
//#define PP_Windows 0x52
//#define PP_Lsa 0x42
//#define PP_Antimalware 0x32
//#define PP_CodeGen 0x22
//#define PP_AuthentiCode 0x12
//#define PPL_NONE 0x00
//
//#define IOCTL_DELETE_SELFDRV               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x100, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENABLE_SYMBOL                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x101, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DISABLE_SYMBOL               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x102, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//#define IOCTL_GET_EVENT                    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1000, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Enbale_SandBox               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1003, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_SandBox              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1004, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//
//#define IOCTL_READ_KERNEL_MEMORY           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x600, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_WRITE_KERNEL_MEMORY          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x601, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_READ_KERNEL_MEMORY_ONESIZE   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x602, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_WRITE_KERNEL_MEMORY_ONESIZE  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x603, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_READ_MEMORY                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x604, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_READ_MEMORY_GET_ADDRESS      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x605, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_WRITE_TO_KERNEL_MEMORY       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x606, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//#define IOCTL_CHECK_HVM                    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x300, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_INIT_HVM                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x301, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UNLOAD_HVM                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x302, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_EPT_HOOK                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x303, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//
//#define IOCTL_Prohibit_CreateProcess       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x400, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UnProhibit_CreateProcess     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x401, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Prohibit_CreateFile          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x402, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UnProhibit_CreateFile        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x403, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Prohibit_LoadDriver          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x404, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UnProhibit_LoadDriver        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x405, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Prohibit_Modify_Registry     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x406, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UnProhibit_Modify_Registry   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x407, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Protect_Disk                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x408, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UnProtect_Disk               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x409, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Prohibit_UnloadDriver        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x410, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UnProhibit_UnloadDriver      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x411, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_Notifys              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x412, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Enable_Notifys               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x413, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_ObCallback           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x414, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Enable_ObCallback            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x415, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_DSE                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x416, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Enable_DSE                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x417, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ShutDown                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x418, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REBOOT                       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x419, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_FORCE_REBOOT                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x420, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_BLUESCREEN                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x421, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_ObCallback_Hvm       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x422, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Enable_ObCallback_Hvm        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x423, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ProtectProcess_Hvm           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x424, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UnProtectProcess_Hvm         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x425, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_CmpCallback          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x426, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Enable_CmpCallback           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x427, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Enable_HVM_Sandbox           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x428, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_HVM_Sandbox          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x429, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//
//#define IOCTL_Disable_PatchGuard_EFI       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x500, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_PatchGuard_BIOS      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x501, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_PatchGuard_DYNAMIC   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x502, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//#define IOCTL_ENUM_PROCESS		           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_DRIVERS		           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_MINIFILTER              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Scan_MSRHook                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_QUERY_FILE                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_EXCALLBACK              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_SYTSTEMTHREAD           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_IRP_HOOK                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_CREATE_THREAD_NOTIFY    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_CREATE_PROCESS_NOTIFY   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_OB_PROCESS_CALLBACK     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_OB_THREAD_CALLBACK      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_OB_DESKTOP_CALLBACK     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_LOADIMAGE_NOTIFY        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x813, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_REGISTRY_CALLBACK       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x814, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_BUGCHECK_CALLBACK       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x815, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_BUGCHECKREASON_CALLBACK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x816, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_SHUTDOWN_NOTIFY         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x817, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_LASTSHUTDOWN_NOTIFY     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x818, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_FS_NOTIFY               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x819, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_POWERSETTING_NOTIFY     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x820, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_COALESCING_NOTIFY       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x821, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_PRIORIRY_NOTIFY         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x822, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_DBGPRINT_CALLBACK       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x823, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_NMI_CALLBACK            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x824, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_OBJECT_TYPE_TABLE       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x825, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_IO_TIMER                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x826, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_IDT                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x827, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_SSDT                    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x828, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_WFPCALLOUT              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x829, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_PROCESS_THREAD          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x830, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_GDT                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x831, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_UNLOADED_DRIVERS        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x832, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_DRIVER_MAJORFUNCTIONS   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x833, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_SSSDT                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x834, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_PROCESS2                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x835, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_HALPRIVATEDISPATHTABLE  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x836, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_HALDISPATHTABLE         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x837, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_PLUGPLAY_NOTIFY         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x838, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_EMP_CALLBACK            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x839, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_ENUM_PIDDBCACHE_TABLE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x840, METHOD_BUFFERED, FILE_ANY_ACCESS)
//
//
//#define IOCTL_KILL_PROCESS		           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Unload_Driver		           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Hidden_Driver		           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Force_KILL_PROCESS           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Suspend_PROCESS              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Resume_PROCESS               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Hidden_PROCESS               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Force_Hidden_PROCESS         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x907, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Set_PPL                      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x908, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_KILL_PROCESS_DELETE          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x909, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_SET_CRITICAL_PROCESS         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x910, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Enbale_Monitor               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1001, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Disable_Monitor              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1002, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DELETE_FILE                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x911, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_FORCE_DELETE_FILE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x912, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_DELETE_FILE_UNICODE          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x913, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_FORCE_DELETE_UNICODE         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x914, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_LOCK_FILE                    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x915, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_LOCK_FILE_UNICODE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x916, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_MINIFILTER            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x917, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_EXCALLBACK            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x918, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_TERMINATE_THREAD             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x919, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_NOTIFY                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x920, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_MSRHOOK               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x921, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_SSDTHOOK              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x922, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_FLASH_FIRMWARE               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x923, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_LOCK_FIRMWARE                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x924, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Suspend_Thread               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x925, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_Resume_Thread                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x926, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_FORCE_TERMINATE_THREAD       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x927, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_WFP                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x928, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_GET_PROTECT_PID              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x929, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_IRPHOOK               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x930, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_SEARCH_OBJECT_DELETE_FILE    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x931, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_SEARCH_DELETE_FILE_THREAD    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x932, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_SHELLCODE_INJECT_DLL         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x933, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_MODIFY_DRIVER_BASE           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x934, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_MODIFY_DRIVER_NAME_PATH      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x935, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_FORCE_HIDDEN_DRIVER          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x936, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_SET_ENUM_PROCESS_MODE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x937, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_MINIFILTER2           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x938, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_EXECUTE_PATCHGUARD           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x939, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_PROTECT_WINDOW               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x940, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_SET_SANDBOX_PID              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x941, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UNHOOK_SSDT_INLINEHOOK       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x942, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_UNHOOK_SSSDT                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x943, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_REMOVE_PIDDBCACHE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x944, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_THREAD_INJECT_DLL            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x945, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_START_TRUSTEDINSTALLER       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x946, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_MODIFY_PROCESS_TOKEN         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x947, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_CRASH_SYSTEM_SET_COLOR       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x948, METHOD_BUFFERED, FILE_ANY_ACCESS)
//#define IOCTL_EDIT_TASKMGR                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x949, METHOD_BUFFERED, FILE_ANY_ACCESS)
